name: Upload Artifacts in Batches

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Upload first batch of files
        uses: actions/upload-artifact@v4
        with:
          name: 'batch1'
          path: |
            build/**/*.{html,css,js}  # Adjust as per your project
          retention-days: 5

      - name: Upload second batch of files
        uses: actions/upload-artifact@v4
        with:
          name: 'batch2'
          path: |
            build/**/*.{png,jpg,svg}  # Upload image or other file types
          retention-days: 5
